### ISSUE TITLE
(maint) Remove ruby 1.8.7 support from the module

### ISSUE THREAD

**Issue by acidprime** [voxpupuli/puppet-r10k#231]
Its a long time coming, but this needs to happen in the next major version as we are spending way to much time dealing with ruby 1.8.7. Now that Puppet 4 on FOSS ships an embedded ruby stack and r10k 2.x removes 1.8.7 support, the community will need to start looking to upgrade puppet and thus ruby soon anyway.

**Comment by rnelson0** [comment]
Ruby 1.8.7 support will be removed when #288 is complete.

**Comment by rnelson0** [comment]
#288 is complete and 4.0 has been released!
