### ISSUE TITLE
(enhancement) pre-commit hook only validates what's on disk

### ISSUE THREAD

**Issue by binford2k** [voxpupuli/puppet-r10k#234]
And this is a problem because what's on disk may or may not be what's committed. That's why we do the weird git stash in the classroom.

https://github.com/puppetlabs/pltraining-classroom/blob/master/files/pre-commit#L9

**Comment by natemccurdy** [comment]
@binford2k Which has the weird $PWD bug and sometimes loses uncommitted files.

**Comment by rnelson0** [comment]
@binford2k The referenced file line has changed, but I think I can intuit the right lines. That said, is that still up to date, and should this even be in the files directory? It seems like it manages more than just r10k, which has some assumptions, and there are plenty of dedicated puppet webhook repos.

**Comment by rnelson0** [comment]
It looks like you moved away from git stash. I'm going to close this out, let me know if you need this resolved some other way though.
