### ISSUE TITLE
(question/enhancement) Does the mco r10k agent log anywhere?

### ISSUE THREAD

**Issue by Phil0xF7** [voxpupuli/puppet-r10k#237]
How can I detect r10k errors once the the `mco r10k deploy command` has run? When we have a syntax error in the Puppetfile or there is an error running r10k on one of our compile masters we are unable to detect this error.

**Comment by acidprime** [comment]
@Phil0xF7 sounds like a great feature request. FYI though, really you should be having users run `r10k puppetfile check` as part of a pre-commit hook, there is an example in the files directory of this module.

**Comment by acidprime** [comment]
@Phil0xF7 also FYI we used to log to mco_output.log but then moved it as json output of the hook itself, https://github.com/acidprime/r10k/blob/master/templates/webhook.bin.erb#L170 so if you are triggering the mco via the hook you can use the resultant value for info. All that said, what kind of information do you think it would have been helpful to have logged exactly? There are some tickets for r10k itself to start logging but I am willing to do the minimum until then .

**Comment by Phil0xF7** [comment]
@acidprime Does the json output from the hook log to /var/log/webhook/access.log? That logfile usually tells me the mco r10k command was triggered which is great but I'd also like to determine the status of the r10k run as well.

For logging, the same info that an 'r10k deploy environment foo -p' would output. So warnings and errors messages. The exit code from the r10k run would also be great.

**Comment by acidprime** [comment]
@Phil0xF7 no when that change as added the output log was removed as its stored in the remote git servers list of pushes ( at least for github). So I would have to take a look at the mcollective agent as I thought I want passing back the output but I have never really sat down to look at it.

**Comment by rnelson0** [comment]
@Phil0xF7 Is this still an outstanding issue for you?

**Comment by Phil0xF7** [comment]
@rnelson0 This is no longer and issue for me.
