### ISSUE TITLE
mcollective agent broke on some systems

### ISSUE THREAD

**Issue by acidprime** [voxpupuli/puppet-r10k#257]
Seems like the new activation code is not correct

**Comment by crazymind1337** [comment]
Hello,
I am having an issue executing `mco rpc r10k deploy environment=feature_r10k`:

`
ERROR	 -> Command exited with non-zero exit code:
                         Command: puppet module --modulepath /etc/puppet/environments/feature_r10k/modules --color false install --version=3.2.0 --force zack/r10k
                         Stdout:
                         Notice: Preparing to install into /etc/puppet/environments/feature_r10k/modules ...
                         Notice: Downloading from https://forgeapi.puppetlabs.com ...
                         Stderr:
                         Error: Could not connect to https://forgeapi.puppetlabs.com
                           There was a network communications problem
                             The error we caught said 'getaddrinfo: Name or service not known'
                             Check your network connection and try again
                         Exit code: 1
`

Executing `r10k deploy environment feature_r10k` on the host itself works fine. 

Is this related to your message?

**Comment by rnelson0** [comment]
@acidprime do you recall details of this? It looks like there are a number of issues/PRs addressing individual MCO issues, hopefully we can close this out.

**Comment by rnelson0** [comment]
I'm going to close this out and address other issues in their individual issues.
