### ISSUE TITLE
Status 42, OK, but it doesn't completely work

### ISSUE THREAD

**Issue by dan-wittenberg** [voxpupuli/puppet-r10k#261]
When I manually run:  umask 0022; mco rpc r10k synchronize -v
master0002.example.com                   : OK
    {:output=>"", :error=>"", :status=>42}

---- r10k#synchronize call stats ----
           Nodes: 4 / 4
     Pass / Fail: 4 / 0

So it seems to think everything is working, but looking on the node it doesn't actually sync all the repos.  There doesn't appear to be any logs or errors indicating why it's not performing the sync.

**Comment by acidprime** [comment]
@dan-wittenberg there is a know issues with PATHS in the current version, if you try the code form 2.x branch it might help ( if your not on Puppet 4)

**Comment by dan-wittenberg** [comment]
I'm actually on PE 2015.2.3 and 2015.3.

**Comment by alexjfisher** [comment]
@dan-wittenberg I'm assuming you're hitting the same problem as I did. See https://github.com/acidprime/r10k/issues/273 for explanation and workaround you could use.

```mco rpc r10k 'deploy production' -v``` gave me output that led me straight to the problem.

**Comment by rnelson0** [comment]
@dan-wittenberg #295 should fix this, can you test against HEAD and verify before we close this?

**Comment by rnelson0** [comment]
@dan-wittenberg actually that's available in v4.0.2 (as puppet/r10k now), no need to point to HEAD.

**Comment by rnelson0** [comment]
@dan-wittenberg I'm going to close this out but let us know in a new issue if you still see this. Thanks!
