### ISSUE TITLE
discussion: r10k deploy environment with no -p argument

### ISSUE THREAD

**Issue by mschuchard** [voxpupuli/puppet-r10k#265]
Recently we had a need to update the control repo of a specific directory environment and then update only one module in this environment.  This need arose because we had a special case directory environment with 1200 modules where one module was only ever deployed at a time in a CI/CD pipeline where the mco r10k was executed remotely on a Jenkins build slave.  The -p argument was causing an enormous slowdown on the CD for obvious reasons.

I took our local fork of this module and added a new possible argument (deploy_control_repo) that ostensibly (to the user) omits the -p argument from the mco r10k deploy 'environment' command.  It worked and I was planning on upstreaming the functionality back here.

Stylistically, what would the preference be for me to add this functionality to this module?  There are multiple methods for doing it and I want to ensure the method is ideal before implementing and PR.

**Comment by igalic** [comment]
@mschuchard does https://github.com/acidprime/r10k/pull/266 address your issue?

**Comment by mschuchard** [comment]
Yes.  Let me add this issue to that PR.

**Comment by rnelson0** [comment]
@mschuchard I'm going to close this issue as the PR addresses it. If the PR author doesn't respond shortly we can look at rebasing the PR, or you can if you'd like. Thanks!
