### ISSUE TITLE
"mco rpc r10k deploy environment=production" not working on Debian 8.3

### ISSUE THREAD

**Issue by crazymind1337** [voxpupuli/puppet-r10k#271]
Hello,

I am currently working on a continuous deployment using r10k and jenkins. The job which triggers the command fails with for all modules given in Puppetfile:

```
ERROR    -> Command exited with non-zero exit code:
Command: puppet module --modulepath /etc/puppet/environments/production/modules --color false install --version=0.0.3 --force croddy/make
Stdout:
Notice: Preparing to install into /etc/puppet/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Stderr:
Error: Could not connect to https://forgeapi.puppetlabs.com
  There was a network communications problem
    The error we caught said 'getaddrinfo: Name or service not known'
    Check your network connection and try again
Exit code: 1
```

I am having just one master which is also a foreman server. So a reinstallation to Ubuntu 14.04 where it is working is not possible.

Is there any fast fix for the issue?

Versions:
puppet 3.8.6
foreman-1.11-rc2
r10k-1.5.1

Update: I have also checked the dns which is working very fine on that machine.

regards
Mike;

**Comment by crazymind1337** [comment]
Sometimes I should think before writing issues, I fixed the problem by myself via:

```
# gem install domain_name
Fetching: unf-0.1.4.gem (100%)
Successfully installed unf-0.1.4
Fetching: domain_name-0.5.20160310.gem (100%)
Successfully installed domain_name-0.5.20160310
Parsing documentation for unf-0.1.4
Installing ri documentation for unf-0.1.4
Parsing documentation for domain_name-0.5.20160310
Installing ri documentation for domain_name-0.5.20160310
Done installing documentation for unf, domain_name after 1 seconds
2 gems installed
```

Can be closed! :)

**Comment by rnelson0** [comment]
@crazymind1337 Is this still an issue for you?

Aside: croddy/make has been updated to v1.0.0 and was donated to Vox Pupuli. You should be on the lookout for puppet/make v1.0.1 coming soon.

**Comment by crazymind1337** [comment]
@rnelson0: I cannot test this, I am not working in the company anymore where I had this issue.

**Comment by rnelson0** [comment]
@crazymind1337 thanks for the update, I will close this out.
