### ISSUE TITLE
MCollective r10k only syncs git based modules

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-r10k#273]
With puppet 4 (AIO packages), the path to 'puppet' has changed.  When mcollective runs r10k, puppet isn't on the path and all forge modules that were going to be synced with 'puppet module install' fail.

mco r10k deploy commands return without reporting any error.

My workaround was to create a symlink on my puppet master.
`ln -s /opt/puppetlabs/bin/puppet /usr/local/bin/puppet`

**Comment by gitlabgis** [comment]
Oh Thanks, 

I don't use Mcollective but I had the same issue as you.

The template https://github.com/acidprime/r10k/blob/master/templates/webhook.bin.erb line 34 should be updated for Puppet 4 path.

Like this:

ENV['PATH'] = '/sbin:/usr/sbin:/bin:/usr/bin:`/opt/puppetlabs/bin:`<%= if @is_pe == true or @is_pe == 'true' then '/opt/puppet/bin' else '/usr/local/bin' end %>'

Until that, I also created a symlink:
```
file {'/usr/local/bin/puppet':
 ensure => link,
 target => '/opt/puppetlabs/bin/puppet'
}
```

Thanks again.

David
