### ISSUE TITLE
Conflict between r10k subclasses and pe_r10k due to `require r10k` in subclasses

### ISSUE THREAD

**Issue by rnelson0** [voxpupuli/puppet-r10k#323]
In init.pp:
```
  # Check if user is declaring both classes
  # Other classes like r10k::webhook is supported but
  # using both classes makes no sense unless given pe_r10k
  # overrides this modules default config
  if defined(Class['pe_r10k']) {
    fail('This module does not support being declared with pe_r10k')
  }
```
The following config at one time worked on a master:
```
include ::pe_r10k
include ::r10k::mcollective
class {'r10k::webhook::config': }
class {'r10k::webhook': }
```
Both webhook.pp and mcollective.pp received the statement `require ::r10k` during the initial modulesync when migrated from acidprime, [here](https://github.com/voxpupuli/puppet-r10k/commit/a2d4ce9b33ebca8186113e6d3204f10b8222401c#diff-99d1e71cb836710a60b0805c80d9b560) and [here](https://github.com/voxpupuli/puppet-r10k/commit/d1fe76d7dee828250bb7000cc93500bd5a7248b5#diff-dca4e79d8eeeb74d4d8d77cf12eb6e14) respectively.

Investigate if the require is *ahem* required or if it was added in error. This is related to #282 and should be included in the same release as #268.

**Comment by esalberg** [comment]
Thank you!  Let me know if there's anything I can do to help.

**Comment by rnelson0** [comment]
The original commits contributing to this added `$root_user` and `$root_group` back at https://github.com/voxpupuli/puppet-r10k/commit/d1fe76d7dee828250bb7000cc93500bd5a7248b5. I think by namespacing references properly the requires can be removed.
