### ISSUE TITLE
dependency on puppetlabs/gcc which is not v1

### ISSUE THREAD

**Issue by ghoneycutt** [voxpupuli/puppet-r10k#326]
Here's a ticket[1] asking them to merge a PR[2] to make this v1. If they do not want to do this, perhaps we can move the module to Vox Pupuli.

[1] - https://tickets.puppetlabs.com/browse/MODULES-4266
[2] - https://github.com/puppetlabs/puppetlabs-gcc/pull/15

**Comment by 0x6d617474** [comment]
puppetlabs/gcc was dropped as a dependency as of #465

**Comment by Dan33l** [comment]
closed because module `puppet-r10k` module does not depend anymore of `puppetlabs-gcc`
