### ISSUE TITLE
cachedir setting is not idempotent

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-r10k#351]
'puppet apply' and 'puppet agent' produce different results for the same code:

```
 Notice: /Stage[main]/R10k::Config/File[r10k.yaml]/content: 
--- /etc/puppetlabs/r10k/r10k.yaml	2017-03-18 18:42:23.732745000 +0000
+++ /tmp/puppet-file20170318-18579-18zu7r3	2017-03-18 18:46:56.205745000 +0000
@@ -1,5 +1,5 @@
 ---
-:cachedir: /opt/puppetlabs/puppet/cache/r10k
+:cachedir: /opt/puppetlabs/server/data/puppetserver/r10k
 :sources:
   puppet:
     basedir: /etc/puppetlabs/code/environments
```

**Comment by vchepkov** [comment]
This could be a quirk of puppetserver and the fact that it doesn't honor settings of vardir in puppet.conf and instead using master-var-dir from puppetserver.conf, therefore $settings::vardir are different.

**Comment by rnelson0** [comment]
I think that's probably the case. Can you confirm which of cachedir belongs to which command?

**Comment by vchepkov** [comment]
The top one is for puppet apply, bottom for puppetserver
I see this changed back and forward when PE installer is running, since it's using 'puppet apply' and then reverts it when puppetserver compiles catalog.

**Comment by vchepkov** [comment]
puppetlabs-stdlib provides a fact - $::puppet_vardir, it can be used instead of $settings::vardir, IMHO
