### ISSUE TITLE
webhook gems aren't installable

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-r10k#365]
The latest version of rack isn't installable on puppet's ruby 2.1.9.
Up until now, this wasn't a problem as the sinatra gem got installed first and it had a dependency on `rack ~> 1.5`.  (We may as well remove https://github.com/voxpupuli/puppet-r10k/blob/1d0c344b1fee40b6a6d7771ea9b83a9cf07c26c3/manifests/webhook/package.pp#L14-L20)

Sinatra 2.0.0 got released yesterday.  It depends on the newer rack. `rack ~> 2.0`, so we now get
```
Error: Execution of '/opt/puppetlabs/puppet/bin/gem install --no-rdoc --no-ri sinatra' returned 1: ERROR:  Error installing sinatra:
        rack requires Ruby version >= 2.2.2.
Error: /Stage[main]/R10k::Webhook::Package/Package[sinatra]/ensure: change from absent to present failed: Execution of '/opt/puppetlabs/puppet/bin/gem install --no-rdoc --no-ri sinatra' returned 1: ERROR:  Error installing sinatra:
        rack requires Ruby version >= 2.2.2.
```

Due to the `if !defined`, wrapping the installation of sinatra, this is easy enough to work around in my profile.  We should probably fix the issue in the module though.  Is it ok to change
```puppet
package { 'sinatra':
  ensure   => installed,
  provider => $provider,
  before   => Service['webhook'],
}
```
to
```puppet
package { 'sinatra':
  ensure   => '1.4.8',
  provider => $provider,
  before   => Service['webhook'],
}
```
??

**Comment by rnelson0** [comment]
That should be okay, but let's parameterize it with something that defaults to '1.4.8', in case someone wants to provide a specific lower version number.

Re: L14-20, can that be removed? If that's a dependency, seems like the gem provider will install it automatically.

**Comment by alexjfisher** [comment]
When puppet gets around to 14-20 it has nothing to do since rack is already installed (as a sinatra dependency).  Had this not been the case, the module would have been failing since last June (when rack 2.0 came out).
