### ISSUE TITLE
Document bitbucket / stash config / hook_exe behavior 

### ISSUE THREAD

**Issue by khaefeli** [voxpupuli/puppet-r10k#383]
Hi,

It's a little bit complicated to install the webhook support for bitbucket / stash.
Would be great to document it a little bit more. 
e.g. the needed `hook_exe` parameter and that you need to install the [plugin](https://github.com/ngsru/atlassian-external-hooks/) and copy the [stash_mco.rb](https://github.com/voxpupuli/puppet-r10k/blob/master/files/stash_mco.rb) to the bitbucket external-hooks

cheers,
Kevin

**Comment by rnelson0** [comment]
@khaefeli I use bitbucket without the plugin and parameter, so I'm not sure what would go in the documentation. Can you submit a PR with your proposed changes, or at least provide some specific ideas in this ticket? Thanks!

**Comment by khaefeli** [comment]
@rnelson0 submitted an idea ;)

**Comment by bastelfreak** [comment]
closed via https://github.com/voxpupuli/puppet-r10k/pull/384
