### ISSUE TITLE
Request: Move webhook into a gem

### ISSUE THREAD

**Issue by danzilio** [voxpupuli/puppet-r10k#399]
What do we think about breaking the webhook out into a gem? This way it can be installed with the Puppet gem providers and we won't have to templatize the shebang. It would also allow us to break up the code into some more manageable and testable chunks.

I'm happy to do this work, just wanted to see what people thought first.

**Comment by binford2k** [comment]
Your wish is hereby granted! https://github.com/voxpupuli/puppet_webhook

It should be released today in #puppethack (you should be there too!) and then we'll issue a deprecation notice here.

**Comment by danzilio** [comment]
omg! thanks @binford2k! 🎉
