### ISSUE TITLE
r10k deploy not working with a minimal Puppetfile

### ISSUE THREAD

**Issue by intrk** [voxpupuli/puppet-r10k#409]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppetserver-2.8.1-1.el7.noarch but also happened on latest puppet5
- Ruby: rubyversion => 2.1.9
- Distribution: CentOS Linux release 7.4.1708 (Core)
- Module version: puppet-r10k (v6.3.2)

## How to reproduce (e.g Puppet code you use)

r10k puppetfile check

## What are you seeing
[root@puppetmaster temp]# r10k puppetfile check
Failed to evaluate /etc/puppetlabs/code/environments/temp/Puppetfile
Original exception:
/etc/puppetlabs/code/environments/temp/Puppetfile:2: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
mod 'camptocamp-puppetserver',
     ^
/etc/puppetlabs/code/environments/temp/Puppetfile:2: syntax error, unexpected ',', expecting end-of-input
mod 'camptocamp-puppetserver',

## What behaviour did you expect instead

r10k deploy to succeed

**Comment by intrk** [comment]
This is what my Puppetfile looks like.

`mod 'camptocamp-augeas',
mod 'camptocamp-puppetserver',
mod 'gentoo-portage',
mod 'herculesteam-augeasproviders_core',
mod 'puppet-make',
mod 'puppet-r10k',
mod 'puppetlabs-apt',
mod 'puppetlabs-concat',
mod 'puppetlabs-firewall',
mod 'puppetlabs-gcc',
mod 'puppetlabs-git',
mod 'puppetlabs-inifile',
mod 'puppetlabs-postgresql',
mod 'puppetlabs-puppetdb',
mod 'puppetlabs-ruby',
mod 'puppetlabs-stdlib',
mod 'puppetlabs-vcsrepo'

mod "role",
  :git => "git@gitlab.boyg.tech:puppet/role.git",
  :ref => "HEAD"

mod "profile",
  :git => "git@gitlab.boyg.tech:puppet/profile.git",
  :ref => "HEAD"
`

**Comment by intrk** [comment]
Turns out I need to remove commas from the end of the lines. 

Closing.

**Comment by rnelson0** [comment]
FYI, this is the repo for the puppet module, not the application. The application repo for r10k is at https://github.com/puppetlabs/r10k, if you have future issues with the application.

**Comment by intrk** [comment]
Hi Robk,

Yeah, I figured it out. Apologies for the inconvenience caused.
I was hitting my head in my desk for two days and as soon as I submitted
the issue in Github I figured it out. :\

Best regards,
Boyko
