### ISSUE TITLE
Syntax Error in voxpupuli/puppet-r10k/templates/webhook.bin.erb, line 119

### ISSUE THREAD

**Issue by djconn-ncsu** [voxpupuli/puppet-r10k#427]
There is a syntax Error in voxpupuli/puppet-r10k/templates/webhook.bin.erb, line 119

The line 
   $logger.info("Deploying module #{module_name}" in the background.)
should be
   $logger.info("Deploying module #{module_name} in the background.")

Basically, the end of string double-quote is in the wrong place.

## Affected Puppet, Ruby, OS and module versions/distributions

I believe this would affect all versions, but I'm running RHEL 7.

## How to reproduce (e.g Puppet code you use)

Any attempt to commit code to a GitHub branch being watched by Webhook causes this problem.

## What are you seeing
```
systemctl list-units --failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● webhook.service loaded failed failed R10K Webhook Service
```
```
journalctl -u webhook.service
Apr 27 16:06:05 myhost.blah.blah webhook[52019]: /usr/local/bin/webhook:110: syntax error, unexpected keyword_in, expecting ')'
Apr 27 16:06:05 myhost.blah.blah webhook[52019]: $logger.info("Deploying module #{module_name}" in the background.)
Apr 27 16:06:05 myhost.blah.blah webhook[52019]: ^
Apr 27 16:06:05 myhost.blah.blah webhook[52019]: /usr/local/bin/webhook:110: syntax error, unexpected ')', expecting '('
```

**Comment by rnelson0** [comment]
This fix will be in 6.5.1. Thanks!
