### ISSUE TITLE
Integrate puppet_webhook

### ISSUE THREAD

**Issue by dhollinger** [voxpupuli/puppet-r10k#430]
The [puppet_webhook](https://github.com/voxpupuli/puppet_webhook) gem was built to improve and replace the webhook script provided by this module. That gem is now ready for integration into the r10k module.

This issue is to track that task as we need to integrate the gem without replacing the script for the initial release and replace the script entirely in a later release as several configuration options change in the gem vs the script.

**Comment by saz** [comment]
`puppet_webhook` has been archived and this module is using `webhook-go` now. I think this issue can be closed.
