### ISSUE TITLE
Migrate r10k-mcollective to choria

### ISSUE THREAD

**Issue by dhollinger** [voxpupuli/puppet-r10k#431]
The r10k-mcollective plugin that is provided by this module is limiting in that it requires the entire r10k module to utilize. As some users may want to use the mcollective plugin without the full r10k module AND to move the plugin to a centralized location better suited to maintaining Mcollective plugins, we are going to work with @ripienaar to migrate the plugin to a standalone module under the [Choria](https://github.com/choria-io) namespace.

**Comment by jakegroves** [comment]
is this still being looked into?

**Comment by ripienaar** [comment]
Would like to but not an immediate priority. Happy to help someone do it though
