### ISSUE TITLE
Using exec in run_command replaces process and skips notify_* calls

### ISSUE THREAD

**Issue by legooolas** [voxpupuli/puppet-r10k#441]
The `run_command` function uses `exec` with a backgrounded command (using `&`) to run the desired command, which cannot get the exit status of the command, and also replaces the running webhook binary (forked from the parent) with this command.

This means that anything expected to run after calling `run_command` no longer works.

Not sure if the affected Puppet, Ruby, OS etc versions are required, but here's what I'm using currently:
 - Puppet : 4.10.12
 - Ruby : 2.1.9p490 (provided by Puppet PC1 install)
 - Distribution : CentOS 7.5
 - Module version : 6.6.0 (latest at time of writing)

How to reproduce:
 - Use slack notifications and upgrade to puppet-r10k 6.6.0

What are you seeing:
 - No Slack notifications of r10k updates

Expected behaviour:
 - Slack notifications of r10k run with success/failure status

**Comment by stanleyz** [comment]
I fixed that in #458 waiting for merge
