### ISSUE TITLE
support the "proxy" general setting

### ISSUE THREAD

**Issue by kenyon** [voxpupuli/puppet-r10k#468]
The "proxy" general setting should be supported: https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#proxy

This should be a configurable parameter in `manifests/r10k::config` and a corresponding update would need to be made to `templates/r10k.yaml.erb` to insert the setting.

Workaround is to make the proxy settings individually in `git_settings` and `forge_settings`.

**Comment by dhoppe** [comment]
This issue was solved by #487.
