### ISSUE TITLE
webhook.yml file fails due to having a relative pathname

### ISSUE THREAD

**Issue by m0kuj1n** [voxpupuli/puppet-r10k#664]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.13
- Ruby: 2.7.8p225
- Distribution: Rocky 8
- Module version: 13.0.0

## How to reproduce (e.g Puppet code you use)

Upgrade r10k module from 10.30.0 to 13.0.0 and removed mcollective configuration.
Note 10.3.0 is no longer compatible with newer Puppet stdlib as it fails with the error:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown function: 'is_function_available'. (file: /etc/puppetlabs/code/environments/feature_branch/modules/r10k/manifests/params.pp, line: 64, column: 11) on node pmaster-test`

## What are you seeing

Puppet run fails due to file path not being fully-qualified

## What behaviour did you expect instead

Complete Puppet run installing new webhook

## Output log

`Error: Failed to apply catalog: Parameter path failed on File[webhook.yml]: File paths must be fully qualified, not 'webhook.yml' (file: /etc/puppetlabs/code/environments/feature_branch/modules/r10k/manifests/webhook/config.pp, line: 6)`

**Comment by kenyon** [comment]
Can you provide the code you're using?

The default is an absolute path, so I guess you are passing a relative path in your code. https://github.com/voxpupuli/puppet-r10k/blob/6edc75d369c03bab2ffe4ad36b5bcefc0f901b52/manifests/webhook.pp#L27

**Comment by m0kuj1n** [comment]
Hi,
This is what I have in my Hiera config:
`# Puppet Master Configuration
r10k::webhook::config_path: '/etc/webhook.yaml'
r10k::webhook::config::generate_types: true
r10k::webhook::config::public_key_path: "/etc/puppetlabs/puppet/ssl/certs/%{trusted.certname}.pem"
r10k::webhook::config::private_key_path: "/etc/puppetlabs/puppet/ssl/private_keys/%{trusted.certname}.pem"
r10k::webhook::config::use_mcollective: false
r10k::webhook::config::user: 'r10k'
r10k::webhook::config::pass: <ENCODED BLOCK>
r10k::webhook::config::command_prefix: 'export http_proxy=http://cacheserver:3128;umask 0022;'`

And in the Puppet manifest for our Puppet compilers:
```
class profile::puppetcompiler (
  String $r10k_control_repo_path    = hiera('r10k_control_repo_path'),
  String $r10k_control_repo_host    = hiera('r10k_control_repo_host'),
  String $r10k_control_repo_user    = hiera('r10k_control_repo_user'),
  String $r10k_ssh_key              = hiera('r10k_ssh_key'),
  String $r10k_ssh_pub              = hiera('r10k_ssh_pub'),`
<--SNIP -->
  class { 'r10k':
    sources => {
      'production'       => {
        'remote'  => "${r10k_control_repo_user}@${r10k_control_repo_host}:${r10k_control_repo_path}",
        'basedir' => '/etc/puppetlabs/code/environments',
      },
     'fluffy'           => {
        'remote'  => "${r10k_control_repo_user}@${r10k_control_repo_host}:puppetcontrol/fluffy-control",
        'prefix'  => true,
        'basedir' => '/etc/puppetlabs/code/environments',
      },
    },
  }
  include r10k::webhook::config

  class { 'r10k::webhook':
    require         => Class['r10k::webhook::config'],
  }
```
So we are setting it in Hiera. The block of code which is failing is on line 6 of https://github.com/voxpupuli/puppet-r10k/blob/6edc75d369c03bab2ffe4ad36b5bcefc0f901b52/manifests/webhook/config.pp which does look like a relative path?

**Comment by kenyon** [comment]
Your original error is about `is_function_available`. That was removed in 694db29df59fa48fbdd6bd791f59076a5349afe6 so you must be running v10 or older of this module.

**Comment by kenyon** [comment]
Oh I see, you were saying that's why you upgraded.

**Comment by kenyon** [comment]
I'm not seeing a relative path for `webhook.yml` in your code, so I'm not sure where that's coming from. I'd try a hiera lookup on the puppet server to see what hiera is giving. `sudo puppet lookup --node yourserverfqdn r10k::webhook::config_path`

**Comment by m0kuj1n** [comment]
OK this is what a Hiera lookup from the Puppet server brings up for that environment:

```
[root@pmaster-test ~]# puppet lookup --node pmaster-test  --environment feature_branch --compile --explain  r10k::webhook::config_path 

Searching for "r10k::webhook::config_path"
  Global Data Provider (hiera configuration version 5)
    No such key: "r10k::webhook::config_path"
  Environment Data Provider (hiera configuration version 5)
    Using configuration "/etc/puppetlabs/code/environments/mcairney_puppetfile/hiera.yaml"
    Hierarchy entry "Eyaml hierarchy"
      Path "/etc/puppetlabs/code/environments/mcairney_puppetfile/hieradata/roles/puppetca.yaml"
        Original path: "/etc/puppetlabs/code/environments/mcairney_puppetfile/hieradata/roles/puppetca.yaml"
        Found key: "r10k::webhook::config_path" value: "/etc/webhook.yaml"
```

Which suggests that the value is getting pulled from Hiera correctly?

**Comment by kenyon** [comment]
That looks good. That is a different environment than in your original error, `feature_branch` versus `mcairney_puppetfile`. Is the catalog compilation failing with the same error in `mcairney_puppetfile`?

**Comment by m0kuj1n** [comment]
Yes, feature_branch was my attempt at sanitising the output but obviously missed it in the log output! mcairney_puppetfile is the actual name of the feature branch with the updated module versions, production is the main branch which still has 10.3.0 along with old versions of other modules eg stdlib v 8.6.0. I’m trying to upgrade our modules ahead of upgrading to Puppet 8 and have hit a catch 22 with this particular module

**Comment by m0kuj1n** [comment]
Hi, I've unravelled some of the spaghetti in my Puppet manifest and the Puppet run now completes. With this in mind I think this particular issue can be closed
